### ISSUE TITLE
App doesn't take into account timezone

### ISSUE THREAD

**Issue by 825i** [m-i-n-a-r/birday#170]
My niece was born today. It's 3am in her home country but 7pm now in mine. So it's 3rd November today here, but she was born after midnight on 4th of November.

When I try and set the date as 4th of November (1 day ahead of today), it sets the year automatically 1 year back. I can't set the date 1 day ahead.

Please fix this.

**Comment by m-i-n-a-r** [comment]
That's a really particular case, but i admit it makes sense. At the time of writing, the app lets you select only a date in the past for your current time zone. I'll try to make it possible to select a date one day in the future, to support "corner cases" like yours. Thanks!

**Comment by m-i-n-a-r** [comment]
Fixed in db7062817a5a44c5b7792bedb3a7159cd84d54af. Now the app accepts events one day in the future 😄

**Comment by DominikNovosel** [comment]
You forgot to change the comment in the code to reflect this new "one day after" logic. It might be confusing down the line.

**Comment by m-i-n-a-r** [comment]
Done in 19ad40181e257487b7210a4dd19321f160dcf7c9, sorry 😄
