### ISSUE TITLE
Import from CSV not working 

### ISSUE THREAD

**Issue by vsahishnu** [m-i-n-a-r/birday#338]
Hi team. I am on the version Birday 4.4.3 from Playstore. 

I have a csv which follows the format mentioned in wiki exactly. Still when I do the import, I get the small pop up at the bottom saying "events imported" but non of the records in the csv would have been imported...

Can someone help me with this. 

I am on a Redmi Note 13 pro running Android 14

**Comment by m-i-n-a-r** [comment]
Could you provide the csv itself? You can mask any sensitive data if you want :)

**Comment by vsahishnu** [comment]
[sample.csv](https://github.com/user-attachments/files/16120592/sample.csv)

Does this work?

**Comment by m-i-n-a-r** [comment]
Thanks. I'll take a look and update the issue!

**Comment by vsahishnu** [comment]
Thanks a lot. Do lmk if there is anything I can do :)

**Comment by macmoritz** [comment]
Same issue here. Sadly there is no error message shown.   
The app says "import finished", but the data was not imported.

**Comment by m-i-n-a-r** [comment]
Sorry, forgot to mention: I fixed it! Just be patient, I should publish the update in the next few weeks!

**Comment by vsahishnu** [comment]
Thats awesome m-i-n-a-r. 
Thanks for the help :)

Also if possible, can you share some info on what went wrong??

**Comment by m-i-n-a-r** [comment]
c287ca3d3fd54ce633eb39fb52abc43375788c3d here's the commit. In the previous version, I implemented the support for different separators in the csv, but I did a couple mistakes and I forgot to test :(

**Comment by vsahishnu** [comment]
Ah ok. No issues. Thanks for the info :)

**Comment by bytebolt** [comment]
Thanks for your work on this app. It looks fantastic!
I am still not able to add csv or json in the latest build from June. I originally installed from f-droid which says it's running an older version from 2 months ago, then I tried it with the latest build from the release section. 

Here are my findings:
1) JSON and CSV Import : I get import successful but nothing
2) JSON Export: I see blank curly brackets even tho I have dummy data in {}
3) CSV Export: Works as expected and returns a csv file

**Comment by bytebolt** [comment]
Thank you, it's fixed in yesterday's release
